import {nextErrorNumber} from '../../../common/errorManager/AppCommonErrorCodes'

const authErrosCodes = {
    AUTH_MISSING_TOKEN:nextErrorNumber('AUTH_MISSING_TOKEN'),
    AUTH_NOT_VALID_TOKEN:nextErrorNumber('AUTH_NOT_VALID_TOKEN'),
    AUTH_NOT_VALID_USER:nextErrorNumber('AUTH_NOT_VALID_USER'),
    AUTH_PASSWORD_REQUIRED:nextErrorNumber('AUTH_PASSWORD_REQUIRED'),
    AUTH_MISSING_GOOGLE_TOKEN:nextErrorNumber('AUTH_MISSING_GOOGLE_TOKEN'),
    AUTH_NOT_VALID_GOOGLE_TOKEN:nextErrorNumber('AUTH_NOT_VALID_GOOGLE_TOKEN'),
    AUTH_FAIL_TO_GENERATE_ACCESS:nextErrorNumber('AUTH_FAIL_TO_GENERATE_ACCESS'),
    AUTH_FAIL_TO_GENERATE_PERMISSIONS:nextErrorNumber('AUTH_FAIL_TO_GENERATE_PERMISSIONS'),
    AUTH_MUST_VERIFY_YOUR_EMAIL:nextErrorNumber('AUTH_MUST_VERIFY_YOUR_EMAIL'),
    AUTH_USER_IS_ALREADY_VERIFY:nextErrorNumber('AUTH_USER_IS_ALREADY_VERIFY'),    
    AUTH_DENIED_LEVEL_ACCESS:nextErrorNumber('AUTH_DENIED_LEVEL_ACCESS'),
    AUTH_MASTER_PERMISSIONS_DENIED:nextErrorNumber('AUTH_MASTER_PERMISSIONS_DENIED'),
    AUTH_USER_PERMISSIONS_DENIED:nextErrorNumber('AUTH_USER_PERMISSIONS_DENIED'),
    AUTH_LEVEL_ACCESS_PERMISSIONS_DENIED:nextErrorNumber('AUTH_LEVEL_ACCESS_PERMISSIONS_DENIED'),
} as const;

export {
    authErrosCodes
}