import {nextErrorNumber} from '../../../common/errorManager/AppCommonErrorCodes'

const attributeErrosCodes = {
  ATTRIBUTE_TYPE_ID_IS_NOT_NUMERIC:nextErrorNumber('ATTRIBUTE_TYPE_ID_IS_NOT_NUMERIC'),
  ATTRIBUTE_PROFILE_TYPE_ID_IS_NOT_NUMERIC:nextErrorNumber('ATTRIBUTE_PROFILE_TYPE_ID_IS_NOT_NUMERIC'),
  ATTRIBUTE_ID_IS_NOT_NUMERIC:nextErrorNumber('ATTRIBUTE_ID_IS_NOT_NUMERIC'),
  ATTRIBUTE_ID_NOT_VALID:nextErrorNumber('ATTRIBUTE_ID_NOT_VALID'),
  ATTRIBUTE_NAME_BAD_FORMAT:nextErrorNumber('ATTRIBUTE_NAME_BAD_FORMAT'),
  ATTRIBUTE_DESCRIPTION_BAD_FORMAT:nextErrorNumber('ATTRIBUTE_DESCRIPTION_BAD_FORMAT'),
  ATTRIBUTE_RANGE_ARRAY_BAD_FORMAT:nextErrorNumber('ATTRIBUTE_RANGE_ARRAY_BAD_FORMAT'),
  ATTRIBUTE_PROFILE_ARRAY_BAD_FORMAT:nextErrorNumber('ATTRIBUTE_PROFILE_ARRAY_BAD_FORMAT'),
} as const;

export {
    attributeErrosCodes 
}